### PR TITLE
Support directives without value

### LINKED ISSUE #16: Add support for directives without value
It would be nice to be able to set the `HttpOnly` and `Secure` directives on the [Set-Cookie header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie). Currently it isn't possible as the library expects all directives to have a value.

### PR DESCRIPTION
**Pull request by walbertoibarra**
This closes #16.

### CODE REVIEW

**Comment by evantahler** [comment]
This is looking good! Can you please add a test for this behavior?

**Comment by walbertoibarra** [comment]
Tests added.

**Comment by evantahler** [comment]
awesome! Thank you!

**Comment by evantahler** [comment]
v1.0.2 released with these changes

**Pull request merged**
